version: v2beta1
name: vcluster-knative

vars:
  PLUGIN_IMAGE: ishankhare07/vcluster-knative-serving-plugin
  K3S_IMAGE: rancher/k3s:v1.23.5-k3s1

images:
  knative-dev:
    image: ${PLUGIN_IMAGE}-dev
    dockerfile: ./Dockerfile.dev
    rebuildStrategy: ignoreContextChanges
    buildArgs:
      TARGETARCH: amd64
    target: builder
    buildKit: {}
  knative:
    image: ${PLUGIN_IMAGE}
    dockerfile: ./Dockerfile
    rebuildStrategy: ignoreContextChanges
    buildArgs:
      TARGETARCH: amd64
    target: builder
    buildKit:
      inCluster: {}

deployments:
  vcluster:
    helm:
      chart:
        name: vcluster
        repo: https://charts.loft.sh
        version: 0.10.0
      valuesFiles:
        - plugin.yaml
      values:
        plugin:
          knative-serving-plugin:
            image: ${PLUGIN_IMAGE}
        service:
          type: NodePort
        serviceCIDR: $([ $1 == "dev" ] && vcluster get service-cidr || echo "null")
        rbac:
          clusterRole:
            create: true
          role:
            extended: true
        serviceAccount:
          create: false
          name: default
        syncer:
          readinessProbe:
            enabled: false
          livenessProbe:
            enabled: false


dev:
  vcluster:
    imageSelector: ${PLUGIN_IMAGE}
    terminal:
      command: "./devspace_start.sh"
    ports:
      - port: 2350:2345
    sync:
      - path: ./:/go/vcluster

pipelines:
  build: |-
    # Make sure pull secrets are there
    ensure_pull_secrets --all
    
    # Build the vcluster image
    build_images knative
  build-dev: |-
    # Make sure pull secrets are there
    ensure_pull_secrets --all
    
    # Build the vcluster image
    build_images knative-dev